name: Builds, signs and publishes the WebExtension
on:
  push:
    branches:
      - master

jobs:
  publish-to-amo:
    name: Build and publish the extension
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Pull and checkout source
        uses: actions/checkout@master
      - uses: pnpm/action-setup@v2.2.3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Build and sign the extension
        run: pnpm run sign
        env:
          WEB_EXT_API_KEY: ${{ secrets.AMO_API_KEY }}
          WEB_EXT_API_SECRET: ${{ secrets.AMO_API_SECRET }}
      - name: Upload the signed extension as an artifact
        uses: actions/upload-artifact@v3
        with:
          name: signed-extension
          path: web-ext-artifacts
      - name: Create a release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "web-ext-artifacts/*.xpi"
